// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)
export default {
  sidebar: [
    'index',
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

